### ISSUE TITLE
Unknown key:"technology-name.sct-lab-lab2"

### ISSUE THREAD

**Issue by shelaf** [mexmer/ScienceCostTweakerM#12]
A lab shaped technology name is displayed as Unknown key:"technology-name.sct-lab-lab2".
This technology add Bob's Tech Lab MK2.

![sct-lab-lab2](https://user-images.githubusercontent.com/980272/44506685-7aed6c80-a6e2-11e8-96a0-d1f2572d3628.png)

**Comment by mexmer** [comment]
fixed in latest release
