### ISSUE TITLE
recipe of the lab-alien does not exist

### ISSUE THREAD

**Issue by LovelySanta** [mexmer/ScienceCostTweakerM#14]
I had a [bug report](https://mods.factorio.com/mod/MoreScience/discussion/5b86b5ffdbb473000b788d78) on my MoreScience mod. Afther disabling my mod and SCT the modpack loaded just fine. When enabling SCT with the modpack without MoreScience it already errored out:

![Error message](https://i.imgur.com/hMceY30.png)

You can download his modpack [here](https://we.tl/t-3Yh8o8NufM) and I made a [pastebin with the modlist](https://pastebin.com/6vx3pznV) too.

Kind regards,
lovely_santa

**Comment by mexmer** [comment]
will be resolved in new release. seem lab alien is enabled only when alien artifacts and colored artifacts are both enabled, i had test only for one.
