### ISSUE TITLE
Fertilizer technology unavailable from Bio Industries w/ More Bobs! ?

### ISSUE THREAD

**Issue by GaistH** [mexmer/ScienceCostTweakerM#15]
This is a bit of a weird one, but I'm not sure if it is from an interaction between this mod and Bio Industries + More Bobs! for some reason. The technology for Fertilizer is listed as (unavailable) despite having its dependencies researched already. The only mods that indicate involvement with this technology are Bio Industries (which is the mod that adds it in the first place), ScienceCostTweaker Mod (mexmer) and More Bobs!

Here is a screenshot of what I mean:

![hphdlnt](https://user-images.githubusercontent.com/42808283/44989011-8189a880-af5a-11e8-98a0-d26f42b12279.jpg)

**Comment by mexmer** [comment]
SCT doesn't remove any dependendencies, check first how it behave without SCT with your mod combination.

**Comment by GaistH** [comment]
Quite strange, this tech worked fine previously with just Bio Industries and More Bobs!--but disabling SCT didn't affect it, while disabling More Bobs! added another dependency to fluid handling and makes it researchable.  I'm _certain_ it worked previously, but perhaps a Bio Industries update or something along the line added a tech dependency and More Bobs! was somehow enforcing an old one.  Either way, it wasn't SCT.  Thank you!

![4neooht](https://user-images.githubusercontent.com/42808283/45029934-3b931a00-b018-11e8-9aac-37cec03e62f1.jpg)

**Comment by mexmer** [comment]
thanks for info
