### ISSUE TITLE
Incompatibility with EndgameCombat

### ISSUE THREAD

**Issue by Sacro** [mexmer/ScienceCostTweakerM#2]
This is the only mod that's keeping me from switching to your version!

`Error ModManager.cpp:1024: Failed to load mod "EndgameCombat": __EndgameCombat__/data-updates.lua:8: __EndgameCombat__/prototypes/item/compound-ammo.lua:72: Tech set to unlock recipe 'sct-lab-3', which does not exist?!`

Not sure why this is the case

Raised on his side too https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/issues/67

**Comment by ReikaKalseki** [comment]
This error is raised when a technology contains an unlock for a recipe that does not exist in the game, at least at the time my data-updates script is run.

Do you have such an oversight?

**Comment by Sacro** [comment]
I'm just hunting through code now, never dealt with Lua before

**Comment by mexmer** [comment]
ok, i think, i will split tech loading into stages, because lab recipes are added in final updates, to prevent overrides.

other option will be just to add lab recipe in data stage, without ingredients, that will work too.

**Comment by Sacro** [comment]
Thanks @mexmer :)

**Comment by mexmer** [comment]
should be fixed in 0.16.16 release, can you test it?
[release 0.16.16](https://github.com/mexmer/ScienceCostTweakerM/releases/tag/0.16.16)

**Comment by mexmer** [comment]
if it still doesn't work, reopen it. i was able to load factorio with it
