### ISSUE TITLE
crash when starting the game 0.17.6

### ISSUE THREAD

**Issue by arcs1337** [mexmer/ScienceCostTweakerM#23]
Hey, when i try to start the game with only this mod activated it crashes https://imgur.com/a/pI0UUTY 
Factorio version 0.17.6
Mod version 0.17.0

**Comment by mexmer** [comment]
it's interesting, it did load properly in 0.17.5, i will test it with 0.17.6, i'm planning to eventually fix everything, including migration scripts

**Comment by mexmer** [comment]
this should be fixed in 0.17.1
happened only when military was set to tier3
