### ISSUE TITLE
0.17 - Full B&A + ScienceCostTweakerM

### ISSUE THREAD

**Issue by LaUr3nTiU** [mexmer/ScienceCostTweakerM#24]
Hey.

I've just added all released Bob's and Angel's mods, your mod and a few QOL mods and unfortunately I'm unable to create the Electromagnetism Lab. The Lab Mechanization part requires the "yellow" transport belt (and I'm starting with the gray ones) and "Basic Electronic Board" (the ones that requires solder + basic electronics components + basic circuit board).

Both the Basic Electronic & Circuit Boards are Bob's Electronics > ShinyBobGFX.  The Tier 1 lab and both of it's sub-components are Your Mod > Ange's refining.

Can you please look into this? Thanks!

**Comment by mexmer** [comment]
as i stated on forum topic (and in mod changelog), it's work in progress, mod currently supports only vanilla. support for bobs and angels in 0.17 planned. just not done yet.

**Comment by LaUr3nTiU** [comment]
Oh. I wasn't able to find anything on this when I was looking in the forums the other day. Sorry. Should I close this issue or leave it open?

**Comment by mexmer** [comment]
leave it open, i will close it, when updated version with b&a support is up.
should be soon.

forum post is here
https://forums.factorio.com/viewtopic.php?f=190&t=59596&start=80#p406284

also shinybobs is zombiees mod, but afaik it should not change recipes, only icons

**Comment by mexmer** [comment]
should be fixed now
