### ISSUE TITLE
"modules" research is unavailable with AAI Industries

### ISSUE THREAD

**Issue by OvermindDL1** [mexmer/ScienceCostTweakerM#29]
The `"modules"` research is unavailable when AAI Industries is installed because:

1. AAI Industries makes the `"modules"` research require the `"electric-lab"` research from AAI Industries at:  `aai-industry_0.3.5/prototypes/technology/technology-update.lua:7:util.tech_add_prerequisites("modules", "electric-lab")`
  * This technology is only used as a pre-req for `"modules"` and it unlocks the `"lab"` entity (without the items needed to construct it by SCT, so that should probably be removed and electromagnetism technology should depend on electric-lab anyway, or something like that).
2. SCT (this mod) then disables the `"electric-lab"` technology at:
```lua
ScienceCostTweakerM_0.17.7/tweaks/aai/1_update.lua:62:  if data.raw.technology["electric-lab"] then
ScienceCostTweakerM_0.17.7/tweaks/aai/1_update.lua:63:          data.raw.technology["electric-lab"].enabled = false
```
Interestingly in that same file are the same lines commented out at:
```lua
ScienceCostTweakerM_0.17.7/tweaks/aai/1_update.lua:20:--        if data.raw.technology["electric-lab"] then
ScienceCostTweakerM_0.17.7/tweaks/aai/1_update.lua:21:--                data.raw.technology["electric-lab"].enabled = false
```
Also, elsewhere in the file it actually adjusts the `"electric-lab"` tech to "SCT-ify" it.  I'm guessing that when that was done the lines to disable that research was commented out without actually knowing that the same lines exist again later down in the file.

Without having tested it I'd guess that commenting out (or better yet, outright remove since `git` is used anyway` the above referenced lines (and the `end` line of course) would probably fix it and gate it behind the `"electric-lab"` (that is already edited by SCT anyway) properly?

If anything I'd say that the `"electric-lab"` research should be left enabled and a few other research/lab related technologies should be attached to it too, specifically the electromagnetism lab research should require it and the 'lab' that it enables should be not enabled by it (since the electromagnetism lab technology by SCT enables it too along with the items required to build it).  Either that or the technology should be left disabled and modules should not require it.  :-)

**Comment by OvermindDL1** [comment]
Actually it seems that the electric lab requires a multitude of red research, which is fine, except the electromagnetism lab research unlocks 'those' researches, so they can't depend on each other.  Perhaps if AAI Industries is installed then red the electromagnetism lab should be unlocked by electric lab technology, and the red science ("Sacrificial Electromagnet") should be unlocked in the burner era without requiring the electromagnetism lab since you can put them in AAI Industries burner lab anyway?

**Comment by mexmer** [comment]
problem lies within other mods
there are no such dependencies on electric lab you claim only dependency is modules, and that one doesn't matter, because modules have also dependency on electronics-2, so even after SCT hides lab, it's still researcheable due electronics-2 presence.

https://imgur.com/a/coyRJg1
