### ISSUE TITLE
Cycle in technology tree detected.

### ISSUE THREAD

**Issue by AmatorPhasma** [mexmer/ScienceCostTweakerM#30]
Hi, I found a starting error:

a mod combination of: Angel, Bob and Space Exploration:

Difficulty normal: Cycle in technology tree detected:
sct-lab-lab2
-> space-science-pack
-> se-space-assembling
-> se-space-manufactory
-> se-space-decontamination-facility
-> se-space-data-card
-> se-space-supercomputer-1
-> se-space-catalogue-material-1
-> se-material-science-pack
-> tungsten-processing
-> sct-lab-t4
-> utility-science-pack
-> sct-lab-lab2

I added my log and a save before installing SCT (easier to sync the mods)

[sct_before.zip](https://github.com/mexmer/ScienceCostTweakerM/files/3107722/sct_before.zip)
[factorio-current.log](https://github.com/mexmer/ScienceCostTweakerM/files/3107698/factorio-current.log)

**Comment by mexmer** [comment]
that's issue of SE-SPACE + BOBS , auithor of SE-SPACE made some stupid changes in research tree, that results in cyclic research with bobs plates. nothing i can fix on my side.
