### ISSUE TITLE
Error on Launch

### ISSUE THREAD

**Issue by WiseMack** [mexmer/ScienceCostTweakerM#37]
Trying to launch a Seablock game fails because of the following error.

112.265 Error ModManager.cpp:1332: Failed to load mod "ScienceCostTweakerM": __ScienceCostTweakerM__/data-final-fixes.lua:11: __ScienceCostTweakerM__/sctmlib.lua:23: bad argument #2 of 3 to 'remove' (number expected, got string)
stack traceback:
	[C]: in function 'remove'
	__ScienceCostTweakerM__/sctmlib.lua:23: in function 'lab_input_remove'
	__ScienceCostTweakerM__/tweaks/angelsmods/2_final.lua:5: in main chunk
	[C]: in function 'require'
	__ScienceCostTweakerM__/data-final-fixes.lua:11: in main chunk
stack traceback:
	[C]: in function 'require'
	__ScienceCostTweakerM__/data-final-fixes.lua:11: in main chunk

Included Complete Log File
[factorio-previous.log](https://github.com/mexmer/ScienceCostTweakerM/files/4041995/factorio-previous.log)

**Comment by mexmer** [comment]
as you might see, i have not touched SCT for quite long time. so i have no idea what is last version that it works with. i might look into it somewhere in future if i return to playing factorio, but it will not be soon.

**Comment by mexmer** [comment]
this issue was fixed some time ago by incorporating patch from trainwreck
