### ISSUE TITLE
Lab Overhaul release has wrong ingredient for "ElectroChemics" lab

### ISSUE THREAD

**Issue by ashkante** [mexmer/ScienceCostTweakerM#4]
When crafting Tier 2 lab (ElectroChemics Lab), it requires an "Electromagnetism Lab". But it will not accept the new, overhauled Electromagnetism lab. It still requires the old item (different icon).

Consequently, new ElectroChemics Labs can't be constructed with 0.16.21.

See screenshot:
![image](https://user-images.githubusercontent.com/10826138/39947172-3a28395e-5571-11e8-95a5-0c5ac7980315.png)

**Comment by mexmer** [comment]
that icon is not from my mod, i suspect other mod you have installed is doing this.

**Comment by mexmer** [comment]
i removed second tier 1 lab recipe, not sure if it fix for you, but there are other mods, that get confused by two tier 1 recipes.

**Comment by ashkante** [comment]
Yeah, now it is okay:
![image](https://user-images.githubusercontent.com/10826138/39954988-57d99d0a-55c9-11e8-8318-61aa79ccb5bf.png)

And I found the icon - it is from "ShinyBobGFX (0.16.19)" and from what I can see, it's replacing icons in "iconchoice.lua". But that just drops in the graphical replacement. If I disable that, it's correct:
![image](https://user-images.githubusercontent.com/10826138/39955263-11096ed4-55cc-11e8-81fa-fe00251e97ba.png)

I didn't notice at first that the icon was from another mod - sorry about that :)

**Comment by mexmer** [comment]
hmm, if you have only angels/bobs and SCT it should work, i'm playing mostly with this mods.
i can't guarantee, it will work with others ... although i made some effort to be compatibile with py and omnimatter

anyway, last version has only single level 1 lab recipe and item, so i think it should work now with most mods.

**Comment by ashkante** [comment]
Yeah, it seems to be working even for my combination of mods - let me know if you'd like a full list :)

But anyway, we can probably close this issue. Thanks!
