### ISSUE TITLE
Error loading mods - Angelbob + Madclown

### ISSUE THREAD

**Issue by HellWatcher** [mexmer/ScienceCostTweakerM#41]
Error on startup using most Arch666Angel + Bobingabout + Madclown01 mods
```
Failed to load mods: Difficulty normal: Cycle in technology tree detected.

angels-components-cabling-2
-> tech-green-circuit
-> tech-green-packs
-> angels-components-cabling-2
```

**Comment by HellWatcher** [comment]
Looks like angel overhauled science and building recipes. Not sure when that happened. Not much point to use another mod that changes science recipes too. No real reason to make it compatible in my opinion.

**Comment by mexmer** [comment]
i had not played factorio lately, so didn't update my mod to reflect changes in bobs and angels.
