### ISSUE TITLE
Cannot research "Modules"

### ISSUE THREAD

**Issue by blackcatwrite** [mexmer/ScienceCostTweakerM#42]
I found that with the mods i am currently playing with that i cannot research even though all prerequisites are completed as seen in:
![2020-05-09 10_55_59-Factorio 0 17 79](https://user-images.githubusercontent.com/11021910/81480000-f8714d00-91e3-11ea-87d3-cd177a6003c5.png)
when I look at modules info it points to bob's modules mod>AAI Industry> Circuit Processing > ScienceCostTweaking Mod.
I have other mods installed but not sure how to get a full list without typing them individually. The reason i noticed an issue is radar amplification 4 for big brother mod is locked behind modules. If i can give any more info please let me know so this issue can be fixed.

**Comment by mexmer** [comment]
as you might have noticed, i'm currently not working on mod, except info update (so it can be run used in 0.18) i did not make any changes.

i  might look into it, when i go back to factorio, but i'm not playing the game for half year already, so can't tell, when i can make fix. you can always make pull request with fix.

**Comment by mexmer** [comment]
seems this was already reported here #36
i will check that soon
