### ISSUE TITLE
New version of Angels breaks SCT

### ISSUE THREAD

**Issue by evandy0** [mexmer/ScienceCostTweakerM#43]
This is a heads-up about the NEXT version of angels (currently unreleased dev branch, but coming soon).   Reports from Lovely_Santa are that it breaks SCT.   Thought you'd appreciate a heads-up before everyone started complaining (like the seablock guys).    Cross-posted in your forum as well: https://forums.factorio.com/viewtopic.php?f=190&t=59596&p=494187#p494187

![SCT](https://user-images.githubusercontent.com/12788951/81950830-0f3fe700-95ca-11ea-81f0-881a2c22c505.png)

**Comment by mexmer** [comment]
thanks for info, but i'm currently not playing game, so can't give you eta for fixed released. as for seablock, i will get into contact with trainwreck, since he manages that mod so he might have some ideas how to fix it.

**Comment by evandy0** [comment]
I believe KingArthur already put together a pull request for you on this one...

**Comment by evandy0** [comment]
Any idea when you'll have a minute to push the release with the fix in it?  I see you merged it to develop so I can always grab the hotfix if I need it, but would be nice to get it official...

**Comment by mexmer** [comment]
version with patch is on mod portal
