### ISSUE TITLE
Mod Incompatibility with Bio Industries, wrong recipe for "Burns-out QL Bio processor"

### ISSUE THREAD

**Issue by DarkShadow44** [mexmer/ScienceCostTweakerM#45]
Probably a minor issue, but when "Bio Industries" is installed, it adds a second recipe for "Burns-out QL Bio processor", using eletric furnace and wooden rails... That should probably be removed.

**Comment by mexmer** [comment]
what mod you mean by bio industries?

angels bio?

**Comment by DarkShadow44** [comment]
This one: https://mods.factorio.com/mod/Bio_Industries

**Comment by mexmer** [comment]
added fixed by mistake, didn't have time to check it yet
