### ISSUE TITLE
Mod Incompatibility with PyCoal+Angels, gold science pack uncraftable

### ISSUE THREAD

**Issue by DarkShadow44** [mexmer/ScienceCostTweakerM#46]
This is a more severe but a bit complicated issue.
Using
- Bob's mods
- Angel's Refining
- PyCoal touched by an Angel (+ Dependencies)

The gold science pack has no recipe. Would you mind looking into that?

**Comment by mexmer** [comment]
not sure when i have time to check on this, i have not played factorio recently, but from my experience, combining PY with anything else is mess and disaster.

gold science pack is crafted from RED + GREEN + BLUE (unless bob changed it), so if py breaks that pack ... my code doesn't alter gold science pack recipe

**Comment by DarkShadow44** [comment]
Ah sorry, this was an issue with PyCoal touched by an Angel.

**Comment by mexmer** [comment]
thanks for letting me know. it's not that i don't like py, i played with it a lot in past, just combining py with anything is pain, except few mods.
