### ISSUE TITLE
Unplayable... :(

### ISSUE THREAD

**Issue by CurlyFlow** [mexmer/ScienceCostTweakerM#49]
So ive installed some new version of a mod breaking 0.18.26.
So ive installed the latest 0.18.28. 

This version i also cant play because SCT is broken. Now i cant play anymore :( Please fix! Thanks!

> 0.000 2020-05-30 20:51:48; Factorio 0.18.28 (build 52459, win64, steam)
>    0.000 Operating system: Windows 10 (version 1909) 
>    0.000 Program arguments: "D:\Programme\Steam\SteamLibrary\steamapps\common\Factorio\bin\x64\Factorio.exe" "--wait-to-close" "12904" 
>    0.000 Read data path: D:/Programme/Steam/SteamLibrary/steamapps/common/Factorio/data
>    0.000 Write data path: C:/Users/Christoph/AppData/Roaming/Factorio [306955/487129MB]
>    0.000 Binaries path: D:/Programme/Steam/SteamLibrary/steamapps/common/Factorio/bin
>    0.009 System info: [CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, 16 cores, RAM: 7430/32688 MB, page: 10630/37552 MB, virtual: 4335/134217727 MB, extended virtual: 0 MB]
>    0.009 Display options: [FullScreen: 1] [VSync: 0] [UIScale: automatic (100.0%)] [Native DPI: 1] [Screen: 255] [Special: lmw] [Lang: de]
>    0.016 Available displays: 2
>    0.016  [0]: \\.\DISPLAY1 - NVIDIA GeForce RTX 2080 SUPER {0x05, [0,0], 3840x2160, 32bit, 60Hz}
>    0.016  [1]: \\.\DISPLAY2 - NVIDIA GeForce RTX 2080 SUPER {0x01, [3840,0], 1920x1080, 32bit, 60Hz}
>    0.052 [Direct3D11] Display: 0, Output: 0, DisplayAdapter: 0, RenderingAdapter: 0; d3dcompiler_47.dll
>    0.140 Initialised Direct3D[0]: NVIDIA GeForce RTX 2080 SUPER; id: 10de-1e81; driver: nvldumdx.dll 26.21.14.4166
>    0.140   D3D Feature Level: 11.1, DXGI 1.5+, SwapChain: 3,flip-discard,-,-,-,none
>    0.140   [Local Video Memory] Budget: 6808MB, CurrentUsage: 2MB, Reservation: 0/3604MB
>    0.140   [Non-Local Vid.Mem.] Budget: 14709MB, CurrentUsage: 0MB, Reservation: 0/7763MB
>    0.140   Tiled resources: Tier 2
>    0.141   Unified Memory Architecture: No
>    0.141   BGR 565 Supported: Yes
>    0.141   MaximumFrameLatency: 3, GPUThreadPriority: 0
>    0.141 Graphics settings preset: very-high
>    0.141   Dedicated video memory size 8010 MB
>    0.169 Desktop composition is active.
>    0.170 Graphics options: [Graphics quality: high] [Video memory usage: all] [Light scale: 100%] [DXT: high-quality] [Color: 32bit]
>    0.170                   [Max threads (load/render): 32/16] [Max texture size: 0] [Tex.Stream.: 0] [Rotation quality: normal] [Other: STDC] [B:0,C:0,S:100]
>    0.205 DSound: Starting _dsound_update thread
>    0.205 DSound: Enter _dsound_update; tid=312
>    0.420 Loading mod settings A Sea Block Config 0.4.0 (settings.lua)
>    0.420 Loading mod settings angelsaddons-crawlertrain 0.1.3 (settings.lua)
>    0.420 Loading mod settings auto-research-18 5.1.4 (settings.lua)
>    0.421 Loading mod settings AutoDeconstruct 0.1.18 (settings.lua)
>    0.421 Loading mod settings bobenemies 0.18.5 (settings.lua)
>    0.421 Loading mod settings bobinserters 0.18.3 (settings.lua)
>    0.421 Loading mod settings Bottleneck 0.11.3 (settings.lua)
>    0.421 Script @__Bottleneck__/settings.lua:131: working - green none
>    0.421 Script @__Bottleneck__/settings.lua:131: no_power - red alert
>    0.421 Script @__Bottleneck__/settings.lua:131: no_fuel - red alert
>    0.421 Script @__Bottleneck__/settings.lua:131: no_recipe - off none
>    0.421 Script @__Bottleneck__/settings.lua:131: no_input_fluid - red alert
>    0.421 Script @__Bottleneck__/settings.lua:131: no_research_in_progress - white pause small
>    0.421 Script @__Bottleneck__/settings.lua:131: no_minable_resources - red stop
>    0.421 Script @__Bottleneck__/settings.lua:131: low_input_fluid - yellow alert
>    0.421 Script @__Bottleneck__/settings.lua:131: low_power - yellow alert
>    0.421 Script @__Bottleneck__/settings.lua:131: disabled_by_control_behavior - white stop small
>    0.421 Script @__Bottleneck__/settings.lua:131: disabled_by_script - white stop small
>    0.421 Script @__Bottleneck__/settings.lua:131: fluid_ingredient_shortage - red alert
>    0.421 Script @__Bottleneck__/settings.lua:131: fluid_production_overload - yellow pause
>    0.421 Script @__Bottleneck__/settings.lua:131: item_ingredient_shortage - red alert
>    0.421 Script @__Bottleneck__/settings.lua:131: item_production_overload - yellow pause
>    0.421 Script @__Bottleneck__/settings.lua:131: marked_for_deconstruction - off none
>    0.421 Script @__Bottleneck__/settings.lua:131: missing_required_fluid - red alert
>    0.421 Script @__Bottleneck__/settings.lua:131: missing_science_packs - red alert
>    0.421 Script @__Bottleneck__/settings.lua:131: waiting_for_source_items - red alert
>    0.421 Script @__Bottleneck__/settings.lua:131: waiting_for_space_in_destination - yellow pause
>    0.421 Script @__Bottleneck__/settings.lua:131: waiting_to_launch_rocket - off none
>    0.421 Loading mod settings clock 0.18.0 (settings.lua)
>    0.422 Loading mod settings Dectorio 0.10.8 (settings.lua)
>    0.422 Loading mod settings Enhanced_Map_Colors 1.5.3 (settings.lua)
>    0.422 Loading mod settings even-distribution 0.3.18 (settings.lua)
>    0.422 Loading mod settings Fill4Me 0.9.2 (settings.lua)
>    0.423 Loading mod settings helmod 0.10.22 (settings.lua)
>    0.423 Loading mod settings Honk 4.1.0 (settings.lua)
>    0.424 Loading mod settings lightorio 0.18.5 (settings.lua)
>    0.424 Loading mod settings nicefill 0.1.17 (settings.lua)
>    0.425 Loading mod settings production-monitor 0.18.2 (settings.lua)
>    0.425 Loading mod settings Squeak Through 1.8.0 (settings.lua)
>    0.425 Loading mod settings VehicleSnap 1.18.3 (settings.lua)
>    0.426 Loading mod settings Warehousing 0.3.0 (settings.lua)
>    0.426 Loading mod settings bobores 0.18.3 (settings.lua)
>    0.427 Loading mod settings bobtech 0.18.3 (settings.lua)
>    0.427 Loading mod settings LogisticTrainNetwork 1.13.8 (settings.lua)
>    0.427 Loading mod settings bobplates 0.18.8 (settings.lua)
>    0.428 Loading mod settings rso-mod 6.0.9 (settings.lua)
>    0.428 Loading mod settings ScienceCostTweakerM 0.18.1 (settings.lua)
>    0.429 Loading mod settings bobassembly 0.18.5 (settings.lua)
>    0.429 Loading mod settings bobelectronics 0.18.1 (settings.lua)
>    0.430 Loading mod settings boblogistics 0.18.9 (settings.lua)
>    0.430 Loading mod settings bobmining 0.18.1 (settings.lua)
>    0.431 Loading mod settings bobpower 0.18.6 (settings.lua)
>    0.431 Loading mod settings bobrevamp 0.18.5 (settings.lua)
>    0.432 Loading mod settings bobwarfare 0.18.6 (settings.lua)
>    0.432 Loading mod settings Actual_Craft_Time 0.5.3 (settings.lua)
>    0.433 Loading mod settings angelsrefining 0.11.11 (settings.lua)
>    0.433 Loading mod settings bobmodules 0.18.3 (settings.lua)
>    0.434 Loading mod settings bobvehicleequipment 0.18.1 (settings.lua)
>    0.435 Loading mod settings LoaderRedux 1.5.2 (settings.lua)
>    0.435 Loading mod settings PickerAtheneum 1.2.1 (settings.lua)
>    0.436 Loading mod settings angelsaddons-warehouses 0.5.1 (settings.lua)
>    0.436 Loading mod settings angelspetrochem 0.9.9 (settings.lua)
>    0.437 Loading mod settings LandfillPainting 0.4.0 (settings.lua)
>    0.437 Loading mod settings Nanobots 3.2.7 (settings.lua)
>    0.438 Loading mod settings PickerExtended 4.1.2 (settings.lua)
>    0.439 Loading mod settings SpaceMod 0.5.1 (settings.lua)
>    0.440 Loading mod settings angelsindustries 0.4.1 (settings.lua)
>    0.441 Loading mod settings CircuitProcessing 0.3.2 (settings.lua)
>    0.441 Loading mod settings A Sea Block Config 0.4.0 (settings-updates.lua)
>    0.442 Loading mod settings angelsaddons-crawlertrain 0.1.3 (settings-updates.lua)
>    0.443 Loading mod settings angelsrefining 0.11.11 (settings-updates.lua)
>    0.443 Loading mod settings angelsindustries 0.4.1 (settings-updates.lua)
>    0.447 Loading mod core 0.0.0 (data.lua)
>    0.510 Loading mod base 0.18.28 (data.lua)
>    0.707 Loading mod A Sea Block Config 0.4.0 (data.lua)
>    0.810 Loading mod AfraidOfTheDark 1.0.25 (data.lua)
>    0.912 Loading mod angelsaddons-crawlertrain 0.1.3 (data.lua)
>    1.016 Loading mod auto-research-18 5.1.4 (data.lua)
>    1.117 Loading mod bobenemies 0.18.5 (data.lua)
>    1.230 Loading mod bobinserters 0.18.3 (data.lua)
>    1.332 Loading mod boblibrary 0.18.9 (data.lua)
>    1.434 Loading mod Bottleneck 0.11.3 (data.lua)
>    1.532 Loading mod CJs_QoL_Research_Ver1 1.0.0 (data.lua)
>    1.634 Loading mod clock 0.18.0 (data.lua)
>    1.731 Loading mod Dectorio 0.10.8 (data.lua)
>    1.836 Loading mod Enhanced_Map_Colors 1.5.3 (data.lua)
>    1.936 Loading mod even-distribution 0.3.18 (data.lua)
>    2.038 Loading mod Explosive Excavation 1.1.7 (data.lua)
>    2.144 Loading mod Fill4Me 0.9.2 (data.lua)
>    2.245 Loading mod FNEI 0.3.4 (data.lua)
>    2.349 Loading mod helmod 0.10.22 (data.lua)
>    2.456 Loading mod Honk 4.1.0 (data.lua)
>    2.558 Loading mod KS_Power 0.4.0 (data.lua)
>    2.663 Loading mod lightorio 0.18.5 (data.lua)
>    2.764 Loading mod nicefill 0.1.17 (data.lua)
>    2.866 Loading mod OpteraLib 0.2.1 (data.lua)
>    2.969 Loading mod production-monitor 0.18.2 (data.lua)
>    3.074 Loading mod some-zoom 0.18.2 (data.lua)
>    3.180 Loading mod textplates 0.5.2 (data.lua)
>    3.305 Loading mod VehicleSnap 1.18.3 (data.lua)
>    3.417 Loading mod Warehousing 0.3.0 (data.lua)
>    3.530 Loading mod WaterWell 1.0.21 (data.lua)
>    3.644 Loading mod bobequipment 0.18.1 (data.lua)
>    3.774 Loading mod bobores 0.18.3 (data.lua)
>    3.901 Loading mod bobtech 0.18.3 (data.lua)
>    4.029 Loading mod LogisticTrainNetwork 1.13.8 (data.lua)
>    4.153 Loading mod OutpostPlanner 1.1.4 (data.lua)
>    4.276 Loading mod bobplates 0.18.8 (data.lua)
>    4.432 Loading mod rso-mod 6.0.9 (data.lua)
>    4.574 Loading mod ScienceCostTweakerM 0.18.1 (data.lua)
>    4.719 Loading mod bobassembly 0.18.5 (data.lua)
>    4.867 Loading mod bobelectronics 0.18.1 (data.lua)
>    5.010 Loading mod bobgreenhouse 0.18.1 (data.lua)
>    5.150 Loading mod boblogistics 0.18.9 (data.lua)
>    5.321 Loading mod bobmining 0.18.1 (data.lua)
>    5.473 Loading mod bobpower 0.18.6 (data.lua)
>    5.644 Loading mod bobrevamp 0.18.5 (data.lua)
>    5.800 Loading mod bobwarfare 0.18.6 (data.lua)
>    5.975 Loading mod dirtybarrels 0.1.66 (data.lua)
>    6.136 Loading mod Actual_Craft_Time 0.5.3 (data.lua)
>    6.299 Loading mod angelsrefining 0.11.11 (data.lua)
>    6.496 Loading mod bobmodules 0.18.3 (data.lua)
>    6.676 Loading mod bobvehicleequipment 0.18.1 (data.lua)
>    6.857 Loading mod LoaderRedux 1.5.2 (data.lua)
>    7.026 Loading mod PickerAtheneum 1.2.1 (data.lua)
>    7.209 Loading mod angelsaddons-warehouses 0.5.1 (data.lua)
>    7.385 Loading mod angelspetrochem 0.9.9 (data.lua)
>    7.585 Loading mod LandfillPainting 0.4.0 (data.lua)
>    7.772 Loading mod Nanobots 3.2.7 (data.lua)
>    7.966 Loading mod PickerExtended 4.1.2 (data.lua)
>    8.159 Loading mod SpaceMod 0.5.1 (data.lua)
>    8.348 Loading mod angelsaddons-pressuretanks 0.5.1 (data.lua)
>    8.534 Loading mod angelssmelting 0.6.7 (data.lua)
>    8.741 Loading mod angelsbioprocessing 0.7.9 (data.lua)
>    8.951 Loading mod angelsindustries 0.4.1 (data.lua)
>    9.162 Loading mod CircuitProcessing 0.3.2 (data.lua)
>    9.352 Loading mod SeaBlock 0.4.5 (data.lua)
>    9.542 Loading mod base 0.18.28 (data-updates.lua)
>    9.745 Loading mod AfraidOfTheDark 1.0.25 (data-updates.lua)
>    9.939 Loading mod angelsaddons-crawlertrain 0.1.3 (data-updates.lua)
>   10.133 Loading mod bobenemies 0.18.5 (data-updates.lua)
>   10.327 Loading mod bobinserters 0.18.3 (data-updates.lua)
>   10.525 Loading mod Dectorio 0.10.8 (data-updates.lua)
>   10.718 Loading mod Enhanced_Map_Colors 1.5.3 (data-updates.lua)
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is small-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is compilatron
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is medium-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is big-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is behemoth-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is small-spitter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is medium-spitter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is big-spitter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is behemoth-spitter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-big-piercing-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-huge-acid-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-huge-explosive-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-giant-poison-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-giant-fire-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-titan-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-behemoth-biter
>   10.718 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-leviathan-biter
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-big-electric-spitter
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-huge-explosive-spitter
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-huge-acid-spitter
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-giant-fire-spitter
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-giant-poison-spitter
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-titan-spitter
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-behemoth-spitter
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-leviathan-spitter
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-robot-gun-drone
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-robot-laser-drone
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-robot-flamethrower-drone
>   10.719 Script @__Enhanced_Map_Colors__/data-updates.lua:154: k is bob-robot-plasma-drone
>   10.912 Loading mod KS_Power 0.4.0 (data-updates.lua)
>   11.105 Loading mod lightorio 0.18.5 (data-updates.lua)
>   11.298 Loading mod Squeak Through 1.8.0 (data-updates.lua)
>   11.491 Loading mod textplates 0.5.2 (data-updates.lua)
>   11.685 Loading mod bobequipment 0.18.1 (data-updates.lua)
>   11.882 Loading mod bobores 0.18.3 (data-updates.lua)
>   12.076 Loading mod bobtech 0.18.3 (data-updates.lua)
>   12.270 Loading mod bobplates 0.18.8 (data-updates.lua)
>   12.469 Loading mod ScienceCostTweakerM 0.18.1 (data-updates.lua)
>   12.664 Loading mod bobassembly 0.18.5 (data-updates.lua)
>   12.863 Loading mod bobelectronics 0.18.1 (data-updates.lua)
>   13.059 Loading mod bobgreenhouse 0.18.1 (data-updates.lua)
>   13.253 Loading mod boblogistics 0.18.9 (data-updates.lua)
>   13.453 Loading mod bobmining 0.18.1 (data-updates.lua)
>   13.649 Loading mod bobpower 0.18.6 (data-updates.lua)
>   13.862 Loading mod bobrevamp 0.18.5 (data-updates.lua)
>   14.068 Loading mod bobwarfare 0.18.6 (data-updates.lua)
>   14.276 Loading mod dirtybarrels 0.1.66 (data-updates.lua)
>   14.480 Loading mod angelsrefining 0.11.11 (data-updates.lua)
>   14.697 Loading mod bobmodules 0.18.3 (data-updates.lua)
>   14.881 Loading mod bobvehicleequipment 0.18.1 (data-updates.lua)
>   15.064 Loading mod angelsaddons-warehouses 0.5.1 (data-updates.lua)
>   15.243 Loading mod angelspetrochem 0.9.9 (data-updates.lua)
>   15.456 Loading mod LandfillPainting 0.4.0 (data-updates.lua)
>   15.637 Loading mod Nanobots 3.2.7 (data-updates.lua)
>   15.823 Loading mod angelsaddons-pressuretanks 0.5.1 (data-updates.lua)
>   16.003 Loading mod angelssmelting 0.6.7 (data-updates.lua)
>   16.219 Loading mod angelsbioprocessing 0.7.9 (data-updates.lua)
>   16.452 Loading mod angelsindustries 0.4.1 (data-updates.lua)
>   16.699 Loading mod CircuitProcessing 0.3.2 (data-updates.lua)
>   16.886 Loading mod SeaBlock 0.4.5 (data-updates.lua)
>   17.076 Loading mod A Sea Block Config 0.4.0 (data-final-fixes.lua)
>   17.259 Loading mod AfraidOfTheDark 1.0.25 (data-final-fixes.lua)
>   17.441 Loading mod auto-research-18 5.1.4 (data-final-fixes.lua)
>   17.624 Loading mod boblibrary 0.18.9 (data-final-fixes.lua)
>   17.625 Script @__boblibrary__/technology-functions.lua:474: Running technology prerequisite cleanup...
>   17.629 Script @__boblibrary__/technology-functions.lua:418: stack traceback:
> 	__boblibrary__/technology-functions.lua:418: in function 'get_prerequisites_in_tree_cached'
> 	__boblibrary__/technology-functions.lua:433: in function 'has_prerequisite_in_tree_only_cached'
> 	__boblibrary__/technology-functions.lua:458: in function 'get_redundant_prerequisites_smart_cached'
> 	__boblibrary__/technology-functions.lua:476: in function 'prerequisite_cleanup'
> 	__boblibrary__/data-final-fixes.lua:1: in main chunk
>   17.629 Script @__boblibrary__/error-functions.lua:13: Technology bio-farm does not exist.
>   17.629 Script @__boblibrary__/technology-functions.lua:418: stack traceback:
> 	__boblibrary__/technology-functions.lua:418: in function 'get_prerequisites_in_tree_cached'
> 	__boblibrary__/technology-functions.lua:433: in function 'has_prerequisite_in_tree_only_cached'
> 	__boblibrary__/technology-functions.lua:458: in function 'get_redundant_prerequisites_smart_cached'
> 	__boblibrary__/technology-functions.lua:476: in function 'prerequisite_cleanup'
> 	__boblibrary__/data-final-fixes.lua:1: in main chunk
>   17.629 Script @__boblibrary__/error-functions.lua:13: Technology bio-farm does not exist.
>   17.629 Script @__boblibrary__/technology-functions.lua:439: stack traceback:
> 	__boblibrary__/technology-functions.lua:439: in function 'has_prerequisite_in_tree_only_cached'
> 	__boblibrary__/technology-functions.lua:458: in function 'get_redundant_prerequisites_smart_cached'
> 	__boblibrary__/technology-functions.lua:476: in function 'prerequisite_cleanup'
> 	__boblibrary__/data-final-fixes.lua:1: in main chunk
>   17.629 Script @__boblibrary__/error-functions.lua:13: Prerequisite technology bio-farm does not exist.
>   17.629 Script @__boblibrary__/technology-functions.lua:418: stack traceback:
> 	__boblibrary__/technology-functions.lua:418: in function 'get_prerequisites_in_tree_cached'
> 	__boblibrary__/technology-functions.lua:433: in function 'has_prerequisite_in_tree_only_cached'
> 	__boblibrary__/technology-functions.lua:458: in function 'get_redundant_prerequisites_smart_cached'
> 	__boblibrary__/technology-functions.lua:476: in function 'prerequisite_cleanup'
> 	__boblibrary__/data-final-fixes.lua:1: in main chunk
>   17.629 Script @__boblibrary__/error-functions.lua:13: Technology bio-farm does not exist.
>   17.818 Loading mod Dectorio 0.10.8 (data-final-fixes.lua)
>   18.042 Loading mod Warehousing 0.3.0 (data-final-fixes.lua)
>   18.242 Loading mod bobtech 0.18.3 (data-final-fixes.lua)
>   18.440 Loading mod LogisticTrainNetwork 1.13.8 (data-final-fixes.lua)
>   18.444 Script @__LogisticTrainNetwork__/data-final-fixes.lua:88: [LTN] found 3214 items, 199 fluids, 11 locomotives, 19 wagons
>   18.641 Loading mod bobplates 0.18.8 (data-final-fixes.lua)
>   18.839 Loading mod rso-mod 6.0.9 (data-final-fixes.lua)
>   19.027 Loading mod ScienceCostTweakerM 0.18.1 (data-final-fixes.lua)
>   19.030 Script @__ScienceCostTweakerM__/sctmlib.lua:13: SCT: science connect started
>   19.035 Script @__ScienceCostTweakerM__/sctmlib.lua:13: SCT: science connect finished - processed 1063 technologies
>   19.222 Loading mod bobelectronics 0.18.1 (data-final-fixes.lua)
>   19.470 Loading mod angelsrefining 0.11.11 (data-final-fixes.lua)
>   19.681 Loading mod LoaderRedux 1.5.2 (data-final-fixes.lua)
>   19.867 Loading mod PickerAtheneum 1.2.1 (data-final-fixes.lua)
>   20.056 Loading mod angelspetrochem 0.9.9 (data-final-fixes.lua)
>   20.263 Loading mod PickerExtended 4.1.2 (data-final-fixes.lua)
>   20.454 Loading mod SpaceMod 0.5.1 (data-final-fixes.lua)
>   20.455 Script @__boblibrary__/technology-functions.lua:234: stack traceback:
> 	__boblibrary__/technology-functions.lua:234: in function 'add_prerequisite'
> 	__SpaceMod__/prototypes/technology-bobs.lua:88: in main chunk
> 	[C]: in function 'require'
> 	__SpaceMod__/data-final-fixes.lua:12: in main chunk
>   20.455 Script @__boblibrary__/error-functions.lua:13: Prerequisite technology speed-module-8 does not exist.
>   20.456 Script @__boblibrary__/technology-functions.lua:234: stack traceback:
> 	__boblibrary__/technology-functions.lua:234: in function 'add_prerequisite'
> 	__SpaceMod__/prototypes/technology-bobs.lua:89: in main chunk
> 	[C]: in function 'require'
> 	__SpaceMod__/data-final-fixes.lua:12: in main chunk
>   20.456 Script @__boblibrary__/error-functions.lua:13: Prerequisite technology effectivity-module-8 does not exist.
>   20.456 Script @__boblibrary__/technology-functions.lua:234: stack traceback:
> 	__boblibrary__/technology-functions.lua:234: in function 'add_prerequisite'
> 	__SpaceMod__/prototypes/technology-bobs.lua:91: in main chunk
> 	[C]: in function 'require'
> 	__SpaceMod__/data-final-fixes.lua:12: in main chunk
>   20.456 Script @__boblibrary__/error-functions.lua:13: Prerequisite technology productivity-module-8 does not exist.
>   20.456 Script @__boblibrary__/technology-functions.lua:234: stack traceback:
> 	__boblibrary__/technology-functions.lua:234: in function 'add_prerequisite'
> 	__SpaceMod__/prototypes/technology-bobs.lua:97: in main chunk
> 	[C]: in function 'require'
> 	__SpaceMod__/data-final-fixes.lua:12: in main chunk
>   20.456 Script @__boblibrary__/error-functions.lua:13: Prerequisite technology energy-shield-equipment-6 does not exist.
>   20.456 Script @__boblibrary__/technology-functions.lua:234: stack traceback:
> 	__boblibrary__/technology-functions.lua:234: in function 'add_prerequisite'
> 	__SpaceMod__/prototypes/technology-bobs.lua:104: in main chunk
> 	[C]: in function 'require'
> 	__SpaceMod__/data-final-fixes.lua:12: in main chunk
>   20.456 Script @__boblibrary__/error-functions.lua:13: Prerequisite technology electric-energy-accumulators-4 does not exist.
>   20.641 Loading mod angelssmelting 0.6.7 (data-final-fixes.lua)
>   20.846 Loading mod ShinyIcons 0.18.1 (data-final-fixes.lua)
>   21.037 Loading mod angelsindustries 0.4.1 (data-final-fixes.lua)
>   21.259 Loading mod SeaBlock 0.4.5 (data-final-fixes.lua)
>   21.492 Checksum for core: 3316124904
>   21.492 Checksum of base: 708703854
>   21.492 Checksum of A Sea Block Config: 2261857758
>   21.492 Checksum of AfraidOfTheDark: 2330519148
>   21.492 Checksum of angelsaddons-crawlertrain: 2527883300
>   21.492 Checksum of auto-research-18: 1160218178
>   21.492 Checksum of AutoDeconstruct: 934032342
>   21.492 Checksum of bobenemies: 3040364297
>   21.492 Checksum of bobinserters: 168175694
>   21.492 Checksum of boblibrary: 3663059181
>   21.492 Checksum of Bottleneck: 1184369145
>   21.492 Checksum of CJs_QoL_Research_Ver1: 3129412096
>   21.492 Checksum of clock: 3722216337
>   21.492 Checksum of Dectorio: 85460838
>   21.492 Checksum of Enhanced_Map_Colors: 1391224849
>   21.492 Checksum of even-distribution: 434966918
>   21.492 Checksum of Explosive Excavation: 4198308750
>   21.492 Checksum of Fill4Me: 2117421323
>   21.492 Checksum of flib: 0
>   21.492 Checksum of FNEI: 2077394332
>   21.492 Checksum of helmod: 3468685269
>   21.492 Checksum of Honk: 3477523997
>   21.492 Checksum of KS_Power: 493562781
>   21.492 Checksum of lightorio: 346778405
>   21.492 Checksum of nicefill: 3405985557
>   21.492 Checksum of OpteraLib: 1428482756
>   21.492 Checksum of PlannerCore: 0
>   21.492 Checksum of production-monitor: 1441656420
>   21.492 Checksum of some-zoom: 1299693085
>   21.492 Checksum of Squeak Through: 2042158127
>   21.492 Checksum of stdlib: 0
>   21.492 Checksum of textplates: 2023599305
>   21.492 Checksum of VehicleSnap: 726116391
>   21.492 Checksum of Warehousing: 1532936239
>   21.492 Checksum of WaterWell: 3712036297
>   21.492 Checksum of bobequipment: 2171673949
>   21.492 Checksum of boblocale: 0
>   21.492 Checksum of bobores: 2992663872
>   21.492 Checksum of bobtech: 279840677
>   21.492 Checksum of LogisticTrainNetwork: 3255828574
>   21.492 Checksum of OutpostPlanner: 1480445408
>   21.492 Checksum of bobplates: 3078520835
>   21.492 Checksum of rso-mod: 2850742254
>   21.492 Checksum of ScienceCostTweakerM: 1919823837
>   21.492 Checksum of bobassembly: 3686392896
>   21.492 Checksum of bobelectronics: 1069687461
>   21.492 Checksum of bobgreenhouse: 3828947702
>   21.492 Checksum of boblogistics: 1408459658
>   21.492 Checksum of bobmining: 1434125394
>   21.492 Checksum of bobpower: 988467601
>   21.492 Checksum of bobrevamp: 394740161
>   21.492 Checksum of bobwarfare: 3407797938
>   21.492 Checksum of dirtybarrels: 2918180519
>   21.492 Checksum of Actual_Craft_Time: 3068536029
>   21.492 Checksum of angelsrefining: 3322543046
>   21.492 Checksum of bobmodules: 2867155780
>   21.492 Checksum of bobvehicleequipment: 1662738641
>   21.492 Checksum of LoaderRedux: 3766821361
>   21.492 Checksum of PickerAtheneum: 3996666538
>   21.492 Checksum of angelsaddons-warehouses: 3223258270
>   21.492 Checksum of angelspetrochem: 654808952
>   21.492 Checksum of LandfillPainting: 2726891558
>   21.492 Checksum of Nanobots: 3667720581
>   21.492 Checksum of PickerExtended: 3740101087
>   21.492 Checksum of SpaceMod: 1859268849
>   21.492 Checksum of angelsaddons-pressuretanks: 2568456394
>   21.492 Checksum of angelssmelting: 4155167227
>   21.492 Checksum of angelsbioprocessing: 343326740
>   21.492 Checksum of ShinyIcons: 1370494641
>   21.492 Checksum of angelsindustries: 3194129086
>   21.492 Checksum of CircuitProcessing: 3353213449
>   21.492 Checksum of SeaBlock: 1945991553
>   21.492 Checksum of angelsaddons-newlocales: 0
>   21.492 Checksum of SeaBlockMetaPack: 0
>   21.794 Error ModManager.cpp:1508: Error in assignID: technology with name 'bio-farm' does not exist.
> 
> Source: sct-bio-science-pack (technology).
>   21.941 Initial atlas bitmap size is 16384
>   21.942 Created atlas bitmap 2048x752 [icon, not-compressed, mipmap, linear-minification, linear-magnification, linear-mip-level]
>   21.948 Texture processor created (2048). GPU accelerated compression Supported: yes, Enabled: yes/yes. Test passed. YCoCgDXT PSNR: 35.83, BC3 PSNR: 33.82
>   21.958 Parallel Sprite Loader initialized (threads: 15)
>   21.986 Sprites loaded
>   22.001 Generated mipmaps (5) for atlas [0] of size 2048x752   
>   22.001 Custom mipmaps uploaded.
>   22.004 Custom inputs active: 33
>   22.007 Factorio initialised
>   22.012 Mods to disable:Fehler beim Laden der Mods: Error in assignID: technology with name 'bio-farm' does not exist.
> 
> Source: sct-bio-science-pack (technology).
> 
> Mods, die deaktiviert werden müssen:
> • ScienceCostTweakerM (0.18.1)
>   42.216 Info AppManager.cpp:1226: Restarting Factorio
>   42.222 Quitting: user-quit.
>   42.326 Steam API shutdown.
>   42.332 Goodbye
>

**Comment by michaelkrymski** [comment]
#47 My response at the bottom with the video fixes this issue. It is a hotfix so it may not work for you, however. I wish you luck! Discord if you need any help: BlazingFlame#5003.

**Comment by michaelkrymski** [comment]
Is there such a thing as a spoiler in Github? That log is awfully long.

**Comment by mexmer** [comment]
forgot to close it, was fixed already some time ago
