### ISSUE TITLE
Seablocks Military sience pack uncraftable

### ISSUE THREAD

**Issue by Durngor** [mexmer/ScienceCostTweakerM#5]
The "Weapons Testing Circuit Board" is currently uncraftable, making The military sience pack impossible (FNEI can't find a recipe either)

**Comment by mexmer** [comment]
with bobs and angels it is craftable, in vanilla also.

if it's uncraftable for you, that means some mod interfere with SCT recipes.

post list of your mods, and i might look into it.

**Comment by mexmer** [comment]
also don't depend on FNEI too much, it has been already proven multiple times, that it can't find everything.

anyway, if you look into SCT science tab, you should have military pack (gray icon - name Ablative weapon testing kit) + 5 items on that line. if you don't have 5 items on that line, some mod is removing items.

whole military pack tech is unlocked trough military 2 research, that has not changed since Uberwaffe added this

![image](https://user-images.githubusercontent.com/5429727/39964879-77f71e6c-568e-11e8-8946-5b87d6bfa648.png)

**Comment by Durngor** [comment]
For seablocks (the modpack I am running including SCT), when it changed to version 2.0, Seablocks replaced coal with charcoal. I guess this is what kills this recipe. Is this something you can do on your side or should I to contact Trainwreck for this issue?

**Comment by mexmer** [comment]
carbon is in bobs and in angels, so you should have it.
anyways don't use version 0.16.20 or newer with seablock, it's not compatibile, trainwreck needs to adopt to new SCT.

Although tbh. i have not tested any version past 0.16.15 with seablock, and seablock itself was built against 0.16.10.

**Comment by Durngor** [comment]
The module is not the problem, the Weapons Testing Circuit Board (the full blue board) is. All the followup reciepies work (both carbon related and the other parts of military sience pack). I will try to update it local to require charcoal instead of coal, since it is the only pack I currently play.

**Comment by Durngor** [comment]
type = "recipe",
		name = "sct-mil-circuit1",
		category = "crafting",
		subgroup = "sct-sciencepack-mil",
		order = "g[mil]-f[circuit1]",
		expensive = 
		{
			enabled = false,
			energy_required = 3,
			ingredients =
			{
				{type="item", name="electronic-circuit", amount=5},
				{type="item", name="charcoal", amount=12}
			},
			results = 
			{
				{type="item", name="sct-mil-circuit1", amount=1},
				{type="item", name="sct-waste-ironcopper", amount=1}
			},
			main_product = "sct-mil-circuit1",
		},
		normal = 
		{
			enabled = false,
			energy_required = 1,
			ingredients =
			{
				{type="item", name="electronic-circuit", amount=2},
				{type="item", name="charcoal", amount=5}
			},
			results = 
			{
				{type="item", name="sct-mil-circuit1", amount=1},
				{type="item", name="sct-waste-ironcopper", amount=1}
			},
			main_product = "sct-mil-circuit1",
		},
	},
This is what I have done and what made the mods work together again (for you and for others with the same problem). The data can be found under prototypes/recipes/intermediates.lua (I really just replaced "coal" with "charcoal")

**Comment by mexmer** [comment]
problem is, that seablock disables some technologies (intentionaly), and change also some other stuff, so it needs to be fixed on side of seablock, not mine, because it has specific progression and limitations
