### ISSUE TITLE
[BUG] Agriculture Modules usable in science pack assembly machines

### ISSUE THREAD

**Issue by KiwiHawk** [mexmer/ScienceCostTweakerM#51]
[AgrModulesTest.zip](https://github.com/mexmer/ScienceCostTweakerM/files/5649678/AgrModulesTest.zip)

Agriculture Modules shouldn't be usable in assembly machines making science packs. Only happens when both Bob's Modules and SCT are active.

See attached save. I did previously have Creative Mod but removed that from the save.

**Comment by LovelySanta** [comment]
Found the culprit:
https://github.com/mexmer/ScienceCostTweakerM/blob/7360a505152a21380d343005ad77bd13eb4f08d0/tweaks/productivity-limitations.lua#L1-L26

An easy fix would be to change line
https://github.com/mexmer/ScienceCostTweakerM/blob/7360a505152a21380d343005ad77bd13eb4f08d0/tweaks/productivity-limitations.lua#L25
with
```lua
	if mods["angelsrefining"] then
		for _, recipe_name in pairs(finallist) do
			angelsmods.functions.allow_productivity(recipe_name)
		end
	else
		bobmods.lib.module.add_productivity_limitations(finallist)
	end
```

A more optimized solution would be to just rewrite the file...
