### ISSUE TITLE
Incompatibility with PyAL

### ISSUE THREAD

**Issue by mecejide** [mexmer/ScienceCostTweakerM#53]
The game is impossible with this mod and PyAL, because none of the SCTM labs accept Py science packs.

**Comment by mexmer** [comment]
@kingarthur91 can you please look at that? i think you doing stuff with py, so might be better if you check this

**Comment by kingarthur91** [comment]
ya ill look into it. pretty sure we just need to add it to the lab that handles chem sci

**Comment by KiwiHawk** [comment]
I've decided to remove Py compatibility. It would take too much work for little gain.

**Comment by kingarthur91** [comment]
Probably for the best. If it's really wanted would be easier to do from the ground up as it's own thing given the amount of work anyway
