### ISSUE TITLE
Gold science pack unlocked twice

### ISSUE THREAD

**Issue by KiwiHawk** [mexmer/ScienceCostTweakerM#56]
I tried this with bob's and angels (no Sea Block). Gold science pack is unlocked by both Complex Science Expertise as well as Alien Research. Alien research requires gold science packs and alien science packs.

The gold science pack recipe unlock just needs to be removed from alien research. Every thing else is fine.

This is just a minor bug, not game breaking at all.

![image](https://user-images.githubusercontent.com/59639/104379587-8af59780-558e-11eb-8664-b6fc2536ad14.png)

**Comment by mexmer** [comment]
hmm, i will need to recheck removal function, because this should be removed here, since gold science pack is already unlock prior this technology.
