### ISSUE TITLE
No Research with aii + Angel + Bob Possible

### ISSUE THREAD

**Issue by Mindflay42** [mexmer/ScienceCostTweakerM#57]
The burner Lab Only accepts the level 2 package (the red one)

But one can only handcraft the Burner Experiment

The whole thing has already been reported in the mod portal but I hope that it will be seen here faster

Many Thanks
https://mods.factorio.com/mod/ScienceCostTweakerM/discussion/60008a3fd0ec261f05a1bdb1

**Comment by mexmer** [comment]
please send list of mods you use

AAI + angels + bobs has been tested and works (including bobs steam phase), only exception is angels industry technology overhaul, which is not supported yet.
