### ISSUE TITLE
Sea Block - Weapons Testing Circuit Board

### ISSUE THREAD

**Issue by randomsprint** [mexmer/ScienceCostTweakerM#6]
Currently doing a Seablock 0.16 playthrough with the science cost tweaker. It looks like the weapons testing circuit board requires 5 coal, which has been replaced with charcoal / carbon / carbon pellets. Would be nice to modify the recipe to not require coal. Perhaps 5 carbon pellets and 2 basic circuit boards?

**Comment by mexmer** [comment]
don't use current version of SCT with seablock, use version from 1st post of Seablock thread, and wait until trainwrecks adopts for changes.
