### ISSUE TITLE
Mechanical Refining not researchable (Bob + Angles)

### ISSUE THREAD

**Issue by dlathro1** [mexmer/ScienceCostTweakerM#60]
See Screenshot below
![Screenshot (2)](https://user-images.githubusercontent.com/29345785/112543981-dac1bd80-8d8c-11eb-88dc-8c40364c2039.png)

angels industry technology overhaul is not enabled

Mod List:
[mod-list (2).txt](https://github.com/mexmer/ScienceCostTweakerM/files/6207936/mod-list.2.txt)

**Comment by dlathro1** [comment]
I did some digging and fixed the problem by adding Angle's Refining as an optional dependency.

**Comment by mexmer** [comment]
i will check it, what you found means, that mod loading order matters. thanks for info.

**Comment by Neko14789** [comment]
It seems that this might also be a Problem with other things, i also was running bob, angels or bob, angels, AAI and both get problems with the Techtree at multiple points, for example also with solder research.

**Comment by mexmer** [comment]
@dlathro1 i checked your setup, and when i removed everything down to angels and bobs and sct, this doesn't happen, so i believe some other mods changes dependendencies for mechanical refining. tbh. SCT doesn't touch angels stuff, except bio token from bioprocessing, and yes mechanicall processing is from refining mod, so if some other mod enabled it, without angels mod ... nothing i can do about.
