### ISSUE TITLE
Bio Science has hidden dependency on Green Science

### ISSUE THREAD

**Issue by KiwiHawk** [mexmer/ScienceCostTweakerM#62]
### Mod list:
- angelsbioprocessing
- angelspetrochem
- angelsrefining
- angelssmelting
- ScienceCostTweakerM

### Settings:
ScienceCostTweaker Mod (mexmer), Angel's biotoken research tier: **tier1**

### Issue:
Optimized biome planner looks like it only requires red science but actually also requires green science. Seedling nest is made is Assembling machine 2 or higher. This is unlocked by Automation 2 which is a green science technology.

![image](https://user-images.githubusercontent.com/59639/117641852-c0c42900-b1da-11eb-8abd-6701127e9609.png)

![image](https://user-images.githubusercontent.com/59639/117642218-26b0b080-b1db-11eb-9823-335b8dfe0098.png)

![image](https://user-images.githubusercontent.com/59639/117644447-97f16300-b1dd-11eb-8f08-4a29873b710e.png)

**Seedling nest**
Recipe name: sct-bio-sample-filling
Recipe category: crafting-with-fluid

### Suggested fix:
Change recipe category from "crafting-with-fluid" to "liquifying". Seedling nest can then be made in either a Liquefier 1 or a Chemical plant 1. Liquefier 1 is unlocked by Basic chemistry which is already a prerequisite of Agricultural Planning.

![image](https://user-images.githubusercontent.com/59639/117643588-ac812b80-b1dc-11eb-87b8-4b9b70cacadf.png)

![image](https://user-images.githubusercontent.com/59639/117646702-2d8df200-b1e0-11eb-85c7-5136c912999b.png)

**Comment by mexmer** [comment]
liquifier looks more logical, early unlock and bioprocessing requires petrochem which add it ... so there are no cons to this change, only pros
