### ISSUE TITLE
Gold and Cobalt in Blue Science

### ISSUE THREAD

**Issue by KiwiHawk** [mexmer/ScienceCostTweakerM#64]
The next Angel's update will make gold ore and cobalt ore unreachable without blue science. 

https://github.com/Arch666Angel/mods/issues/571

I suggest replacing gold plate with silver plate in blue science. And replacing silver plate with gold plate in purple science.

I'm not 100% sure what to replace cobalt steel with in the blue lab core. Brass or Invar?

I'm happy to make a PR for it if you want me to?

**Comment by mexmer** [comment]
thanks for info, i will check it. 
and yes, i'm open to PR, if it will be feasible balance wise. because replacing stuff 1:1 without taking into account processing requirements not always works.

**Comment by KiwiHawk** [comment]
The balance still seems fine to me. Processing is virtually the same.

**Comment by mexmer** [comment]
looks to me that cobalt change is not necessary since it should be available before blue ... gold and silver swap makes sense, in bobs silver is directly smelted (no research) while gold is research dependant.

**Comment by mexmer** [comment]
for now without cobalt, will see if it's needed, then will add that too
