### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by KiwiHawk** [mexmer/ScienceCostTweakerM#67]
Error is caused by technology `sct-lab-alien` having `advanced-research` as a prerequisite. This tech is added by Bob's Technology mod.

To reproduce: Sync with attached save file, then enable Science Cost Tweaker.

[Float.On.zip](https://github.com/mexmer/ScienceCostTweakerM/files/6692518/Float.On.zip)
![image](https://user-images.githubusercontent.com/59639/122889651-158cbf00-d397-11eb-95b1-da5feff10305.png)
![image](https://user-images.githubusercontent.com/59639/122889677-1aea0980-d397-11eb-9186-9267248a3c7c.png)

**Comment by mexmer** [comment]
thanks, will look at it. and will make it as optional dependency inject.

**Comment by mexmer** [comment]
will be fixed in 1.1.8
