### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bigshauny88** [mexmer/ScienceCostTweakerM#68]
Hi, I get this error message when trying to load my game with this mod enabled:

Error while applying migration: ScienceCostTweaker Mod (mexmer): ScienceCostTweaker_1.01.08.lua

LuaForce doesn't contain key technolgies.
stack traceback:
[C]: in function 'index'
...CostTweakerM/migrations/ScienceCostTweaker_1.01.08.lua:2: in main chunk

**Comment by mexmer** [comment]
ah, looks like typo, it's weird it didn't pop when i was loading my save, i will fix it today. thanks for report

**Comment by bigshauny88** [comment]
Oh we got to love the simple things in life 🤣

**Comment by mexmer** [comment]
it's on portal now

**Comment by bigshauny88** [comment]
Thank you
