### ISSUE TITLE
technognology and other typos

### ISSUE THREAD

**Issue by ghost** [mexmer/ScienceCostTweakerM#7]
I found a couple of typos in the locale: 

[sciencecosttweaker.cfg#L12](https://github.com/mexmer/ScienceCostTweakerM/blob/ad40834256abb51f68789f266dddf9fe3fd6cb6d/locale/en/sciencecosttweaker.cfg#L12)
> sct-military=Determines when military research is available.\n\ntier2 : available from tier 2 lab (green,red,**millitary**)\ntier3 : available from tier 3 lab (all except space, hightech)

millitary => military 

[sciencecosttweaker.cfg#L14](https://github.com/mexmer/ScienceCostTweakerM/blob/ad40834256abb51f68789f266dddf9fe3fd6cb6d/locale/en/sciencecosttweaker.cfg#L14)
> sct-lab-scaling=Enables scaling of lab base research speed depending on lab tier\nlab 1 - speed 1, lab 2 - speed 1.1, lab 3 - speed 1.3, lab 4 - speed 1.5 (speed is still affected by research speed **technognology**).

technognology => technology 

[sciencecosttweaker.cfg#L23](https://github.com/mexmer/ScienceCostTweakerM/blob/ad40834256abb51f68789f266dddf9fe3fd6cb6d/locale/en/sciencecosttweaker.cfg#L23)
> military-science-pack=Used by Lab for adapting weapons technology to the local environment, these single use items perform weapons tests and **analyse** the results. 

analyse => analyze (assuming you use US English)

[sciencecosttweaker.cfg#L30](https://github.com/mexmer/ScienceCostTweakerM/blob/ad40834256abb51f68789f266dddf9fe3fd6cb6d/locale/en/sciencecosttweaker.cfg#L30)
> sct-htech-random=Rapidly generates an enormous amount of random numbers mechanically, while being bombarded with virtual particles, to analyze any local bias in **quamtum** fields and in virtual particle matter distortion.

quamtum => quantum

[sciencecosttweaker.cfg#L36](https://github.com/mexmer/ScienceCostTweakerM/blob/ad40834256abb51f68789f266dddf9fe3fd6cb6d/locale/en/sciencecosttweaker.cfg#L36)
> sct-lab-2=**ElectroChemics** Lab

ElectroChemics => Electrochemics or Electrochemical (the 'c' should be lowercase just like the 'm' in electromagnetism)

---

And a few in the changelog: 

[changelog.txt#L18](https://github.com/mexmer/ScienceCostTweakerM/blob/ad40834256abb51f68789f266dddf9fe3fd6cb6d/changelog.txt#L18)
> - **color tint o lab** tier to easier distinguish between different tiers

color tint o lab=>  color tint to lab

[changelog.txt#L50](https://github.com/mexmer/ScienceCostTweakerM/blob/ad40834256abb51f68789f266dddf9fe3fd6cb6d/changelog.txt#L50)
> - force removed upgrade flag from all unlock **technogies** (upgrade technologies are not **searcheable** in tech tree, and neither items they unlock)

technogies => technologies
searcheable => searchable

[changelog.txt#L72](https://github.com/mexmer/ScienceCostTweakerM/blob/ad40834256abb51f68789f266dddf9fe3fd6cb6d/changelog.txt#L72)
> - added bobs logistic **pac** to T3 and T4 lab

pac => pack

**Comment by mexmer** [comment]
thanks i will fix that in next release.
