### ISSUE TITLE
Tech tree cycle with B&A

### ISSUE THREAD

**Issue by KiwiHawk** [mexmer/ScienceCostTweakerM#70]
Seems that Lab 3 still depends on Cobalt processing. I know said Cobalt Steel was swapped out for Brass if Angel's is enabled but that doesn't seem to have happened.

![image](https://user-images.githubusercontent.com/59639/123252349-4a884580-d540-11eb-8226-a1bb2301ec67.png)

Tested using Angel's PR https://github.com/Arch666Angel/mods/pull/608

**Comment by mexmer** [comment]
brass swap is not implemented yet. and afaik change is not live yet, but i will add it, it can be done even now, since brass is unlocked earlier than cobalt.
