### ISSUE TITLE
AAI industry issues 

### ISSUE THREAD

**Issue by Mernom** [mexmer/ScienceCostTweakerM#73]
This mod's handling of the AAI fuel processing tech/recipe is quite outdated. At the moment, it's no longer compatible at all, since fuel processing is required to burner labs, which are required for electricity, which is required for your fuel tech, which is required for the AAI fuel tech.

**Comment by mexmer** [comment]
it's same issue as #72 , so i will close this as duplicate, watch the other one, for updates.
