### ISSUE TITLE
No Lab Available For Single-use ATMOS set

### ISSUE THREAD

**Issue by Wally2123** [mexmer/ScienceCostTweakerM#74]
Good Afternoon,

I'm approaching the point in my game where Single-use ATMOS set is required for science but there is no lab available to use it and steam power can't be unlocked without it.  Is there a setting change that can be used to fix this or will this require code adjustment on your part? 
Looking forward to see this resolved so I can continue using the addon with my game.  Thank you

**Comment by Wally2123** [comment]
The next level of lab; i'm currently using the electromagnetism lab; requires the basic electronic board.  unfortunately to be able to craft them requires steam and anything steam related is locked behind the Single-use ATMOS set.  So my progression is halted at this point.

**Comment by mexmer** [comment]
can you post list of mods? most likely one of mods you use has disabled this item in lab.

**Comment by mexmer** [comment]
some mods change order of science, while SCT accomodates for some changes, even has T0 stage lab, it has limited support for other mods altering science

**Comment by Wally2123** [comment]
AAI Industry
AAI Vehicles: Hauler
AAI Vehicles: Miner
Alien Biomes
Alien Biomes High-Res Terrain
Angels Addons
     C.A.B
     Mass Transit
     Storage Options
     Bioprocessing
     Extended -  Resmelting - Fixed
     Industries
     Infinite Ores
     Petrochemical Processing
     Refining
     Smelting and Smelting Extended
Auto Deconstruct
Beatrix
Better Bot Battery
Bobs
     Adjustable Inserters
     Assembling Machines
     Electronics
     Enemies
     Functions Library
     Gemstones Reloaded
     Greenhouse
     Logistics Belt Redskin and Logistics
     Metals, Chemicals and Intermediates and Extension
     Mining
     Modules
     Ores
     Personal Equipment
     Power
     REvamp
     Technology
     Vehicle Equipment
     Warfare
Bottleneck
Builder Bot Start
Bulk Rail Loader
Car/Tank/Spidertron Locater Button
Crafting Speed REsearch
Disco Science
Even Distribution
Factorio Library and Standard Library
FNEI
Helmod
Informatron
Loader Redux
Madclown01's Extended AngelBob Minerals
MadClown01's Processing
Merging Chests
Module Inserter
Ore Eraser
OSM Lib
P.U.M.P.
Power Grid Comb
Prospector
Rail Signal Planner
Rate Calculator
Reverse Factory
Squeak Through
VehicleSnap
Waterfill
YARM

**Comment by Wally2123** [comment]
Ok so it's not the science mod that's making the mess.  i just did a couple of test games with AAI Industry and ScienceCostTweaker.  Steam Power was readily available from the start and could progress pretty good with no problems, when AAI Industry was added I got to the electrochemics lab just fine and that had the ability to utilize the Single-use ATMOS set.    When Angels and Bobs was added into the mix that's when it becomes the issue.  
ScienceCostTweaker works and is a good mod, it just gets blamed if other mods dont work right with it.

**Comment by mexmer** [comment]
thanks for info, i will need to check coexistence with AAI anyways. tbh. i have not touched it for long time, so it's not up to date with recent changes either to AAI or bobs or angels.

i know they changed lot of things, since i last updated mod ... just didn't have time to update.
