### ISSUE TITLE
Failed to load mods: Difficulty normal: cycle in technology tree detected

### ISSUE THREAD

**Issue by actuallyrisk** [mexmer/ScienceCostTweakerM#77]
Game Version: 1.1 
Mod Version: 1.1.10
Bobs Power Mod: 1.1.7

I recently updated the game to version 1.1 and in combination with those 3 mods there seems to kick a error. This Problem only comes up after installing ScienceCostTweakerM, without and Bobs Power still installed the game starts and works fine.

<img width="408" alt="Screenshot 2023-01-02 215924" src="https://user-images.githubusercontent.com/72505322/210277944-0511cc62-4f91-4d6a-acae-fdf7230e9ec1.png">

**Comment by mexmer** [comment]
seems it's caused by change in techtree in bobpower update, i might look into it sometime later.
