### ISSUE TITLE
Failed to load mods: sct-lab module (technology)

### ISSUE THREAD

**Issue by Dream-Master** [mexmer/ScienceCostTweakerM#78]
After Bob mods was updated i run into this error.
Not sure what was changed in Bobs mod maybe some tech/lab trees are changed
I use a custom Pack. I can provide more infos if you need it.

![image](https://user-images.githubusercontent.com/2970688/210414821-d88cbd42-9a2f-4e90-ab19-22d4b64aa889.png)

**Comment by LovelySanta** [comment]
Occures probably with bob modules, there is a new setting to disable the modules lab

**Comment by Dream-Master** [comment]
will try to disable the module until an update for this mod is out.

**Comment by Dream-Master** [comment]
@LovelySanta can you said me in which bob mod i have to disable it. I was in the ingame mod menu but cant find it.

**Comment by Dream-Master** [comment]
or is the settings inside Sience Cost tweaker mod ?

**Comment by mexmer** [comment]
module lab has been removed from bobs, SCT is not updated yet to reflect this change. so either use older version of bob mods, or disable SCT

**Comment by sweetcornwhiskey** [comment]
I was able to get this to work by enabling the modules lab in the bob's modules configs before loading in SCT. It seems like this is only an issue if the modules lab is disabled.

**Comment by Dream-Master** [comment]
@sweetcornwhiskey can you show me where it can be enabled? is there a config or need it a code change ?

**Comment by sweetcornwhiskey** [comment]
The modules lab can be enabled in the startup settings for Bob's modules:
![Screenshot 2023-01-16 230231](https://user-images.githubusercontent.com/122855135/212831533-f2cc409b-34b3-4f1a-af67-7687fa449f1e.png)

**Comment by Dream-Master** [comment]
ok will try that

**Comment by Dream-Master** [comment]
@KiwiHawk @mexmer @LovelySanta  is there any new version comming out soon fix this issue ?

**Comment by KiwiHawk** [comment]
Yes, I should have a new version out soon.

**Comment by Dream-Master** [comment]
ok cool
