### ISSUE TITLE
Error while applying migration...attempt to index global 'sctm' (a nil value)

### ISSUE THREAD

**Issue by bensmooth** [mexmer/ScienceCostTweakerM#8]
Updated mod version from 0.16.10 (old, I know) to 0.16.41.
I get this error on loading:
```
Error while applying migration: ScienceCostTweaker Mod (mexmer): ScienceCostTweaker_0.16.28.lua

...CostTweakerM__/migrations/ScienceCostTweaker_0.16.28.lua:111: attempt to index global 'sctm' (a nil value)
```
Am I better off just removing this mod, and then re-adding it, or is there an easy fix in the code?

[SeaBlock16.51.zip](https://github.com/mexmer/ScienceCostTweakerM/files/2126298/SeaBlock16.51.zip)

**Comment by Wizarth** [comment]
I also got this. To continue playing, I've downloaded the previous version zip from here, and put it in my mods folder.

**Comment by mexmer** [comment]
should be fixed now
