### ISSUE TITLE
AAI Industry | Electromagnetism lab recipe is not enabled with technology

### ISSUE THREAD

**Issue by sweetcornwhiskey** [mexmer/ScienceCostTweakerM#81]
Mods enabled: AAI Industry, Science Cost Tweaker

After researching the electromagnetism lab technology, the electromagnetism lab cannot be crafted (incorrect behavior).

Electromagnetism lab is researched:

![Screenshot 2023-01-17 000838](https://user-images.githubusercontent.com/122855135/212844326-b5144222-2b9e-483e-966a-91e2f897d15d.png)

Electromagnetism lab is uncraftable:

![Screenshot 2023-01-17 000924](https://user-images.githubusercontent.com/122855135/212844440-495183d6-75c8-40cd-8d16-9904bf8d5068.png)
![Screenshot 2023-01-17 001001](https://user-images.githubusercontent.com/122855135/212844466-bd412ad5-cb20-43a4-83ca-e392793f6037.png)

**Comment by sweetcornwhiskey** [comment]
Ah I see the separate electric labs technology that enables this lab. Still, this a small visual bug

**Comment by mexmer** [comment]
send list of mods you are using, it might be caused by other mod changing technology cycles, or by change in aai technology tree.

idealy if you can send `mod-list.json` and  `mod-settings.dat` from mods folder.

**Comment by sweetcornwhiskey** [comment]
This is for AAI Industry + SCT (only mods enabled). Here's the mod list and settings (uploaded as txt because github doesn't like the file format):

[mod-list.json.txt](https://github.com/mexmer/ScienceCostTweakerM/files/10437609/mod-list.json.txt)
[mod-settings.dat.txt](https://github.com/mexmer/ScienceCostTweakerM/files/10437610/mod-settings.dat.txt)
