### ISSUE TITLE
Error: "attemp to index local '_eff' (a nil value)

### ISSUE THREAD

**Issue by bigyihsuan** [mexmer/ScienceCostTweakerM#9]
I got this bug.

![a](https://i.imgur.com/UJAiVas.png)

Mod List:
![b](https://i.imgur.com/dSv9PgH.png)

I see you know about the issue [here](https://mods.factorio.com/mod/ScienceCostTweakerM/discussion/5b301aa8531c30000bf8bc54), and I'm hoping the issue gets resolved soon.

**Comment by bigyihsuan** [comment]
I also attempted to use the most current commit of the mod with the same modlist, but the same error happens.

**Comment by mexmer** [comment]
Yes i know about the issue, it should be addressed, when mod rework is done ... when? Can’t say, might be few days, might be weeks.

This issue is caused by incorrect handling of mods with extreme difficulty set for technology
