### ISSUE TITLE
Softlock with Bob's, Angel's, and AAI

### ISSUE THREAD

**Issue by KiwiHawk** [mexmer/ScienceCostTweakerM#91]
### Minimum mod list
- aai-industry
- angelspetrochem
- angelsrefining
- bobelectronics
- boblibrary
- bobores
- bobplates
- ScienceCostTweakerM

### T2 Lab softlock
- T2 Lab requires Fast Inserter (or Filter Inserter in come mod configurations) - SCT
-  Fast Inserter requires Basic Electronic Board (`electronic-circuit`) - Base game
- Basic Electronic Board requires Basic Electronic Components - Bob's Electronics mod
- Basic Electronic Components Requires Carbon - MCI
- Carbon requires Steam - Angel's Petrochemical Processing
- Steam requires Boiler - Base game
- Boiler requires tech Steam Power - AAI Industry
- Steam Power requires Green Science - AAI Industry
- Green Science Requires T2 Lab - SCT

![image](https://github.com/mexmer/ScienceCostTweakerM/assets/59639/9554e05d-fbc7-4109-bb7b-01481c101715)

![image](https://github.com/mexmer/ScienceCostTweakerM/assets/59639/32b7a754-a20b-4520-997f-58772c9cccd7)

![image](https://github.com/mexmer/ScienceCostTweakerM/assets/59639/5c9612cd-7c9d-4688-8e17-9f9356faf216)

**Comment by mexmer** [comment]
i would move steam to red science

**Comment by KiwiHawk** [comment]
Yeah, I agree. I'm just trying to figure out which mod is the best to make the change in. I'd say either AAI Industry or Angel's Petrochem. But I need to talk to others about making changes there.

https://discord.com/channels/419526714721566720/1177781301286285333

**Comment by KiwiHawk** [comment]
Fixed in AAI Industry 0.5.22
