### ISSUE TITLE
Science Packs are difficult to search for

### ISSUE THREAD

**Issue by KiwiHawk** [mexmer/ScienceCostTweakerM#92]
It's difficult to find the science packs in the tech tree and production graph. Rename them, adding a consistent prefix.

**Comment by mexmer** [comment]
Search works also by prototypes, so search either for science, or pack should work even without changing label.
although have not played game for a while, did they changed it?

**Comment by KiwiHawk** [comment]
### Before
![image](https://github.com/mexmer/ScienceCostTweakerM/assets/59639/515afdaf-7bb0-4b34-ba24-a0e47589b447)
![image](https://github.com/mexmer/ScienceCostTweakerM/assets/59639/5afeef5c-aeb9-4183-84a1-63ef94c145fc)

### After
![image](https://github.com/mexmer/ScienceCostTweakerM/assets/59639/1bd89470-3f00-4b74-ab5c-57c00fde44fc)
![image](https://github.com/mexmer/ScienceCostTweakerM/assets/59639/76be438e-17d3-4d3b-98ab-34bbb5a51a31)

**Comment by mexmer** [comment]
so i take it, it now search only in labels, and not item names.
since you renaming also technologies, you should fix them for other mods too
bobs
science-pack-gold=Complex Science Expertise
alien-science-pack=Outworld Biology Testing
omni
omnipack-technology=Omnious Experiments

**Comment by KiwiHawk** [comment]
SCT doesn't seem to be renaming any of these science packs. In game, they are still:
- Alien Science Pack
- Gold Science Pack
- Omni Science Pack

![image](https://github.com/mexmer/ScienceCostTweakerM/assets/59639/79bf9f18-1b4b-4759-8751-b130d0928c81)

![image](https://github.com/mexmer/ScienceCostTweakerM/assets/59639/6644b028-4bbe-4309-b4d1-c57abd9058e7)
